### ISSUE TITLE
publish w/ flow & non flow dist

### ISSUE THREAD

**Issue by chrisdostert** [smartGraphQL/PROgraphQL#16]
Hi, great library!

Curious if you would be open to publishing a dist w/ both flow and non flow versions. 

This would allow direct use in non-flow projects in addition to flow projects. The express-graphql dependency you have does this for example:

<img width="288" alt="screen shot 2018-11-06 at 10 37 52 pm" src="https://user-images.githubusercontent.com/2335774/48114637-afb68d80-e214-11e8-9f70-c34462f010c9.png">

Cheers

**Comment by Roldma** [comment]
Got it! thanks for the suggestion!
